version: '3'

services:
  webhook-receiver:
    build:
      context: .
      dockerfile: Dockerfile  # Your Dockerfile for the webhook receiver
    container_name: swr
    ports:
      - "80:80"
    environment:
      - SECRET_KEY=2212
    networks:
      - internal_network

  bitbucket:
    image: atlassian/bitbucket
    container_name: bitbucket
    ports:
      - "7990:7990"
      - "7999:7999"
    volumes:
      - ./bitbucket-data:/var/atlassian/bitbucket
    networks:
      - internal_network

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins-secure
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins-data:/var/jenkins_home
    networks:
      - internal_network

networks:
  internal_network:

volumes:
  bitbucket-data:
  jenkins-data:
